/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TeacherRouteImport } from './routes/teacher'
import { Route as SupervisorRouteImport } from './routes/supervisor'
import { Route as StudentRouteImport } from './routes/student'
import { Route as ParentRouteImport } from './routes/parent'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TeacherIndexRouteImport } from './routes/teacher.index'
import { Route as SupervisorIndexRouteImport } from './routes/supervisor.index'
import { Route as StudentIndexRouteImport } from './routes/student.index'
import { Route as ParentIndexRouteImport } from './routes/parent.index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as TeacherStudentsRouteImport } from './routes/teacher.students'
import { Route as TeacherScheduleRouteImport } from './routes/teacher.schedule'
import { Route as TeacherResourcesRouteImport } from './routes/teacher.resources'
import { Route as TeacherPdfExamsRouteImport } from './routes/teacher.pdf-exams'
import { Route as TeacherLogRouteImport } from './routes/teacher.log'
import { Route as TeacherHomeworkRouteImport } from './routes/teacher.homework'
import { Route as TeacherExamsRouteImport } from './routes/teacher.exams'
import { Route as TeacherAnalyzerRouteImport } from './routes/teacher.analyzer'
import { Route as TeacherAnalyticsRouteImport } from './routes/teacher.analytics'
import { Route as SupervisorTurboRouteImport } from './routes/supervisor.turbo'
import { Route as SupervisorTeachersHubRouteImport } from './routes/supervisor.teachers-hub'
import { Route as SupervisorTeachersRouteImport } from './routes/supervisor.teachers'
import { Route as SupervisorStudentRouteImport } from './routes/supervisor.student'
import { Route as SupervisorSessionsRouteImport } from './routes/supervisor.sessions'
import { Route as SupervisorGradeRouteImport } from './routes/supervisor.grade'
import { Route as SupervisorFollowupsRouteImport } from './routes/supervisor.followups'
import { Route as SupervisorFeedbackRouteImport } from './routes/supervisor.feedback'
import { Route as SupervisorCalendarRouteImport } from './routes/supervisor.calendar'
import { Route as SupervisorAnalyticsRouteImport } from './routes/supervisor.analytics'
import { Route as SupervisorAlertsRouteImport } from './routes/supervisor.alerts'
import { Route as StudentWeeklyRouteImport } from './routes/student.weekly'
import { Route as StudentTrackingRouteImport } from './routes/student.tracking'
import { Route as StudentScheduleRouteImport } from './routes/student.schedule'
import { Route as StudentResourcesRouteImport } from './routes/student.resources'
import { Route as StudentProgressRouteImport } from './routes/student.progress'
import { Route as StudentProfileRouteImport } from './routes/student.profile'
import { Route as StudentPlannerRouteImport } from './routes/student.planner'
import { Route as StudentNotebookRouteImport } from './routes/student.notebook'
import { Route as StudentNextStepRouteImport } from './routes/student.next-step'
import { Route as StudentLessonsRouteImport } from './routes/student.lessons'
import { Route as StudentHomeworkRouteImport } from './routes/student.homework'
import { Route as StudentGrowthRouteImport } from './routes/student.growth'
import { Route as StudentExamsRouteImport } from './routes/student.exams'
import { Route as StudentDailyRouteImport } from './routes/student.daily'
import { Route as StudentAnalyticsRouteImport } from './routes/student.analytics'
import { Route as StudentAchievementsRouteImport } from './routes/student.achievements'
import { Route as ParentWeeklyRouteImport } from './routes/parent.weekly'
import { Route as ParentReportsRouteImport } from './routes/parent.reports'
import { Route as ParentMessagesRouteImport } from './routes/parent.messages'
import { Route as ParentMeetingsRouteImport } from './routes/parent.meetings'
import { Route as ParentGrowthRouteImport } from './routes/parent.growth'
import { Route as ParentFeedbackRouteImport } from './routes/parent.feedback'
import { Route as ParentCompanionRouteImport } from './routes/parent.companion'
import { Route as ParentChildrenRouteImport } from './routes/parent.children'
import { Route as ParentCalendarRouteImport } from './routes/parent.calendar'
import { Route as ParentAnnouncementsRouteImport } from './routes/parent.announcements'
import { Route as AdminUsersRouteImport } from './routes/admin.users'
import { Route as AdminSystemRouteImport } from './routes/admin.system'
import { Route as AdminScheduleRouteImport } from './routes/admin.schedule'
import { Route as AdminRolesRouteImport } from './routes/admin.roles'
import { Route as AdminRegistrationRouteImport } from './routes/admin.registration'
import { Route as AdminCurriculumImportRouteImport } from './routes/admin.curriculum-import'
import { Route as AdminCurriculumRouteImport } from './routes/admin.curriculum'
import { Route as AdminContentRouteImport } from './routes/admin.content'
import { Route as AdminClassesRouteImport } from './routes/admin.classes'
import { Route as AdminCalendarRouteImport } from './routes/admin.calendar'

const TeacherRoute = TeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const SupervisorRoute = SupervisorRouteImport.update({
  id: '/supervisor',
  path: '/supervisor',
  getParentRoute: () => rootRouteImport,
} as any)
const StudentRoute = StudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentRoute = ParentRouteImport.update({
  id: '/parent',
  path: '/parent',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherIndexRoute = TeacherIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TeacherRoute,
} as any)
const SupervisorIndexRoute = SupervisorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SupervisorRoute,
} as any)
const StudentIndexRoute = StudentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StudentRoute,
} as any)
const ParentIndexRoute = ParentIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ParentRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const TeacherStudentsRoute = TeacherStudentsRouteImport.update({
  id: '/students',
  path: '/students',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherScheduleRoute = TeacherScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherResourcesRoute = TeacherResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherPdfExamsRoute = TeacherPdfExamsRouteImport.update({
  id: '/pdf-exams',
  path: '/pdf-exams',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherLogRoute = TeacherLogRouteImport.update({
  id: '/log',
  path: '/log',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherHomeworkRoute = TeacherHomeworkRouteImport.update({
  id: '/homework',
  path: '/homework',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherExamsRoute = TeacherExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherAnalyzerRoute = TeacherAnalyzerRouteImport.update({
  id: '/analyzer',
  path: '/analyzer',
  getParentRoute: () => TeacherRoute,
} as any)
const TeacherAnalyticsRoute = TeacherAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => TeacherRoute,
} as any)
const SupervisorTurboRoute = SupervisorTurboRouteImport.update({
  id: '/turbo',
  path: '/turbo',
  getParentRoute: () => SupervisorRoute,
} as any)
const SupervisorTeachersHubRoute = SupervisorTeachersHubRouteImport.update({
  id: '/teachers-hub',
  path: '/teachers-hub',
  getParentRoute: () => SupervisorRoute,
} as any)
const SupervisorTeachersRoute = SupervisorTeachersRouteImport.update({
  id: '/teachers',
  path: '/teachers',
  getParentRoute: () => SupervisorRoute,
} as any)
const SupervisorStudentRoute = SupervisorStudentRouteImport.update({
  id: '/student',
  path: '/student',
  getParentRoute: () => SupervisorRoute,
} as any)
const SupervisorSessionsRoute = SupervisorSessionsRouteImport.update({
  id: '/sessions',
  path: '/sessions',
  getParentRoute: () => SupervisorRoute,
} as any)
const SupervisorGradeRoute = SupervisorGradeRouteImport.update({
  id: '/grade',
  path: '/grade',
  getParentRoute: () => SupervisorRoute,
} as any)
const SupervisorFollowupsRoute = SupervisorFollowupsRouteImport.update({
  id: '/followups',
  path: '/followups',
  getParentRoute: () => SupervisorRoute,
} as any)
const SupervisorFeedbackRoute = SupervisorFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => SupervisorRoute,
} as any)
const SupervisorCalendarRoute = SupervisorCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => SupervisorRoute,
} as any)
const SupervisorAnalyticsRoute = SupervisorAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => SupervisorRoute,
} as any)
const SupervisorAlertsRoute = SupervisorAlertsRouteImport.update({
  id: '/alerts',
  path: '/alerts',
  getParentRoute: () => SupervisorRoute,
} as any)
const StudentWeeklyRoute = StudentWeeklyRouteImport.update({
  id: '/weekly',
  path: '/weekly',
  getParentRoute: () => StudentRoute,
} as any)
const StudentTrackingRoute = StudentTrackingRouteImport.update({
  id: '/tracking',
  path: '/tracking',
  getParentRoute: () => StudentRoute,
} as any)
const StudentScheduleRoute = StudentScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => StudentRoute,
} as any)
const StudentResourcesRoute = StudentResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => StudentRoute,
} as any)
const StudentProgressRoute = StudentProgressRouteImport.update({
  id: '/progress',
  path: '/progress',
  getParentRoute: () => StudentRoute,
} as any)
const StudentProfileRoute = StudentProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => StudentRoute,
} as any)
const StudentPlannerRoute = StudentPlannerRouteImport.update({
  id: '/planner',
  path: '/planner',
  getParentRoute: () => StudentRoute,
} as any)
const StudentNotebookRoute = StudentNotebookRouteImport.update({
  id: '/notebook',
  path: '/notebook',
  getParentRoute: () => StudentRoute,
} as any)
const StudentNextStepRoute = StudentNextStepRouteImport.update({
  id: '/next-step',
  path: '/next-step',
  getParentRoute: () => StudentRoute,
} as any)
const StudentLessonsRoute = StudentLessonsRouteImport.update({
  id: '/lessons',
  path: '/lessons',
  getParentRoute: () => StudentRoute,
} as any)
const StudentHomeworkRoute = StudentHomeworkRouteImport.update({
  id: '/homework',
  path: '/homework',
  getParentRoute: () => StudentRoute,
} as any)
const StudentGrowthRoute = StudentGrowthRouteImport.update({
  id: '/growth',
  path: '/growth',
  getParentRoute: () => StudentRoute,
} as any)
const StudentExamsRoute = StudentExamsRouteImport.update({
  id: '/exams',
  path: '/exams',
  getParentRoute: () => StudentRoute,
} as any)
const StudentDailyRoute = StudentDailyRouteImport.update({
  id: '/daily',
  path: '/daily',
  getParentRoute: () => StudentRoute,
} as any)
const StudentAnalyticsRoute = StudentAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => StudentRoute,
} as any)
const StudentAchievementsRoute = StudentAchievementsRouteImport.update({
  id: '/achievements',
  path: '/achievements',
  getParentRoute: () => StudentRoute,
} as any)
const ParentWeeklyRoute = ParentWeeklyRouteImport.update({
  id: '/weekly',
  path: '/weekly',
  getParentRoute: () => ParentRoute,
} as any)
const ParentReportsRoute = ParentReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => ParentRoute,
} as any)
const ParentMessagesRoute = ParentMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => ParentRoute,
} as any)
const ParentMeetingsRoute = ParentMeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => ParentRoute,
} as any)
const ParentGrowthRoute = ParentGrowthRouteImport.update({
  id: '/growth',
  path: '/growth',
  getParentRoute: () => ParentRoute,
} as any)
const ParentFeedbackRoute = ParentFeedbackRouteImport.update({
  id: '/feedback',
  path: '/feedback',
  getParentRoute: () => ParentRoute,
} as any)
const ParentCompanionRoute = ParentCompanionRouteImport.update({
  id: '/companion',
  path: '/companion',
  getParentRoute: () => ParentRoute,
} as any)
const ParentChildrenRoute = ParentChildrenRouteImport.update({
  id: '/children',
  path: '/children',
  getParentRoute: () => ParentRoute,
} as any)
const ParentCalendarRoute = ParentCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => ParentRoute,
} as any)
const ParentAnnouncementsRoute = ParentAnnouncementsRouteImport.update({
  id: '/announcements',
  path: '/announcements',
  getParentRoute: () => ParentRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSystemRoute = AdminSystemRouteImport.update({
  id: '/system',
  path: '/system',
  getParentRoute: () => AdminRoute,
} as any)
const AdminScheduleRoute = AdminScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRegistrationRoute = AdminRegistrationRouteImport.update({
  id: '/registration',
  path: '/registration',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCurriculumImportRoute = AdminCurriculumImportRouteImport.update({
  id: '/curriculum-import',
  path: '/curriculum-import',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCurriculumRoute = AdminCurriculumRouteImport.update({
  id: '/curriculum',
  path: '/curriculum',
  getParentRoute: () => AdminRoute,
} as any)
const AdminContentRoute = AdminContentRouteImport.update({
  id: '/content',
  path: '/content',
  getParentRoute: () => AdminRoute,
} as any)
const AdminClassesRoute = AdminClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => AdminRoute,
} as any)
const AdminCalendarRoute = AdminCalendarRouteImport.update({
  id: '/calendar',
  path: '/calendar',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/parent': typeof ParentRouteWithChildren
  '/student': typeof StudentRouteWithChildren
  '/supervisor': typeof SupervisorRouteWithChildren
  '/teacher': typeof TeacherRouteWithChildren
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/classes': typeof AdminClassesRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/curriculum': typeof AdminCurriculumRoute
  '/admin/curriculum-import': typeof AdminCurriculumImportRoute
  '/admin/registration': typeof AdminRegistrationRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/schedule': typeof AdminScheduleRoute
  '/admin/system': typeof AdminSystemRoute
  '/admin/users': typeof AdminUsersRoute
  '/parent/announcements': typeof ParentAnnouncementsRoute
  '/parent/calendar': typeof ParentCalendarRoute
  '/parent/children': typeof ParentChildrenRoute
  '/parent/companion': typeof ParentCompanionRoute
  '/parent/feedback': typeof ParentFeedbackRoute
  '/parent/growth': typeof ParentGrowthRoute
  '/parent/meetings': typeof ParentMeetingsRoute
  '/parent/messages': typeof ParentMessagesRoute
  '/parent/reports': typeof ParentReportsRoute
  '/parent/weekly': typeof ParentWeeklyRoute
  '/student/achievements': typeof StudentAchievementsRoute
  '/student/analytics': typeof StudentAnalyticsRoute
  '/student/daily': typeof StudentDailyRoute
  '/student/exams': typeof StudentExamsRoute
  '/student/growth': typeof StudentGrowthRoute
  '/student/homework': typeof StudentHomeworkRoute
  '/student/lessons': typeof StudentLessonsRoute
  '/student/next-step': typeof StudentNextStepRoute
  '/student/notebook': typeof StudentNotebookRoute
  '/student/planner': typeof StudentPlannerRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/progress': typeof StudentProgressRoute
  '/student/resources': typeof StudentResourcesRoute
  '/student/schedule': typeof StudentScheduleRoute
  '/student/tracking': typeof StudentTrackingRoute
  '/student/weekly': typeof StudentWeeklyRoute
  '/supervisor/alerts': typeof SupervisorAlertsRoute
  '/supervisor/analytics': typeof SupervisorAnalyticsRoute
  '/supervisor/calendar': typeof SupervisorCalendarRoute
  '/supervisor/feedback': typeof SupervisorFeedbackRoute
  '/supervisor/followups': typeof SupervisorFollowupsRoute
  '/supervisor/grade': typeof SupervisorGradeRoute
  '/supervisor/sessions': typeof SupervisorSessionsRoute
  '/supervisor/student': typeof SupervisorStudentRoute
  '/supervisor/teachers': typeof SupervisorTeachersRoute
  '/supervisor/teachers-hub': typeof SupervisorTeachersHubRoute
  '/supervisor/turbo': typeof SupervisorTurboRoute
  '/teacher/analytics': typeof TeacherAnalyticsRoute
  '/teacher/analyzer': typeof TeacherAnalyzerRoute
  '/teacher/exams': typeof TeacherExamsRoute
  '/teacher/homework': typeof TeacherHomeworkRoute
  '/teacher/log': typeof TeacherLogRoute
  '/teacher/pdf-exams': typeof TeacherPdfExamsRoute
  '/teacher/resources': typeof TeacherResourcesRoute
  '/teacher/schedule': typeof TeacherScheduleRoute
  '/teacher/students': typeof TeacherStudentsRoute
  '/admin/': typeof AdminIndexRoute
  '/parent/': typeof ParentIndexRoute
  '/student/': typeof StudentIndexRoute
  '/supervisor/': typeof SupervisorIndexRoute
  '/teacher/': typeof TeacherIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/classes': typeof AdminClassesRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/curriculum': typeof AdminCurriculumRoute
  '/admin/curriculum-import': typeof AdminCurriculumImportRoute
  '/admin/registration': typeof AdminRegistrationRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/schedule': typeof AdminScheduleRoute
  '/admin/system': typeof AdminSystemRoute
  '/admin/users': typeof AdminUsersRoute
  '/parent/announcements': typeof ParentAnnouncementsRoute
  '/parent/calendar': typeof ParentCalendarRoute
  '/parent/children': typeof ParentChildrenRoute
  '/parent/companion': typeof ParentCompanionRoute
  '/parent/feedback': typeof ParentFeedbackRoute
  '/parent/growth': typeof ParentGrowthRoute
  '/parent/meetings': typeof ParentMeetingsRoute
  '/parent/messages': typeof ParentMessagesRoute
  '/parent/reports': typeof ParentReportsRoute
  '/parent/weekly': typeof ParentWeeklyRoute
  '/student/achievements': typeof StudentAchievementsRoute
  '/student/analytics': typeof StudentAnalyticsRoute
  '/student/daily': typeof StudentDailyRoute
  '/student/exams': typeof StudentExamsRoute
  '/student/growth': typeof StudentGrowthRoute
  '/student/homework': typeof StudentHomeworkRoute
  '/student/lessons': typeof StudentLessonsRoute
  '/student/next-step': typeof StudentNextStepRoute
  '/student/notebook': typeof StudentNotebookRoute
  '/student/planner': typeof StudentPlannerRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/progress': typeof StudentProgressRoute
  '/student/resources': typeof StudentResourcesRoute
  '/student/schedule': typeof StudentScheduleRoute
  '/student/tracking': typeof StudentTrackingRoute
  '/student/weekly': typeof StudentWeeklyRoute
  '/supervisor/alerts': typeof SupervisorAlertsRoute
  '/supervisor/analytics': typeof SupervisorAnalyticsRoute
  '/supervisor/calendar': typeof SupervisorCalendarRoute
  '/supervisor/feedback': typeof SupervisorFeedbackRoute
  '/supervisor/followups': typeof SupervisorFollowupsRoute
  '/supervisor/grade': typeof SupervisorGradeRoute
  '/supervisor/sessions': typeof SupervisorSessionsRoute
  '/supervisor/student': typeof SupervisorStudentRoute
  '/supervisor/teachers': typeof SupervisorTeachersRoute
  '/supervisor/teachers-hub': typeof SupervisorTeachersHubRoute
  '/supervisor/turbo': typeof SupervisorTurboRoute
  '/teacher/analytics': typeof TeacherAnalyticsRoute
  '/teacher/analyzer': typeof TeacherAnalyzerRoute
  '/teacher/exams': typeof TeacherExamsRoute
  '/teacher/homework': typeof TeacherHomeworkRoute
  '/teacher/log': typeof TeacherLogRoute
  '/teacher/pdf-exams': typeof TeacherPdfExamsRoute
  '/teacher/resources': typeof TeacherResourcesRoute
  '/teacher/schedule': typeof TeacherScheduleRoute
  '/teacher/students': typeof TeacherStudentsRoute
  '/admin': typeof AdminIndexRoute
  '/parent': typeof ParentIndexRoute
  '/student': typeof StudentIndexRoute
  '/supervisor': typeof SupervisorIndexRoute
  '/teacher': typeof TeacherIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/parent': typeof ParentRouteWithChildren
  '/student': typeof StudentRouteWithChildren
  '/supervisor': typeof SupervisorRouteWithChildren
  '/teacher': typeof TeacherRouteWithChildren
  '/admin/calendar': typeof AdminCalendarRoute
  '/admin/classes': typeof AdminClassesRoute
  '/admin/content': typeof AdminContentRoute
  '/admin/curriculum': typeof AdminCurriculumRoute
  '/admin/curriculum-import': typeof AdminCurriculumImportRoute
  '/admin/registration': typeof AdminRegistrationRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/schedule': typeof AdminScheduleRoute
  '/admin/system': typeof AdminSystemRoute
  '/admin/users': typeof AdminUsersRoute
  '/parent/announcements': typeof ParentAnnouncementsRoute
  '/parent/calendar': typeof ParentCalendarRoute
  '/parent/children': typeof ParentChildrenRoute
  '/parent/companion': typeof ParentCompanionRoute
  '/parent/feedback': typeof ParentFeedbackRoute
  '/parent/growth': typeof ParentGrowthRoute
  '/parent/meetings': typeof ParentMeetingsRoute
  '/parent/messages': typeof ParentMessagesRoute
  '/parent/reports': typeof ParentReportsRoute
  '/parent/weekly': typeof ParentWeeklyRoute
  '/student/achievements': typeof StudentAchievementsRoute
  '/student/analytics': typeof StudentAnalyticsRoute
  '/student/daily': typeof StudentDailyRoute
  '/student/exams': typeof StudentExamsRoute
  '/student/growth': typeof StudentGrowthRoute
  '/student/homework': typeof StudentHomeworkRoute
  '/student/lessons': typeof StudentLessonsRoute
  '/student/next-step': typeof StudentNextStepRoute
  '/student/notebook': typeof StudentNotebookRoute
  '/student/planner': typeof StudentPlannerRoute
  '/student/profile': typeof StudentProfileRoute
  '/student/progress': typeof StudentProgressRoute
  '/student/resources': typeof StudentResourcesRoute
  '/student/schedule': typeof StudentScheduleRoute
  '/student/tracking': typeof StudentTrackingRoute
  '/student/weekly': typeof StudentWeeklyRoute
  '/supervisor/alerts': typeof SupervisorAlertsRoute
  '/supervisor/analytics': typeof SupervisorAnalyticsRoute
  '/supervisor/calendar': typeof SupervisorCalendarRoute
  '/supervisor/feedback': typeof SupervisorFeedbackRoute
  '/supervisor/followups': typeof SupervisorFollowupsRoute
  '/supervisor/grade': typeof SupervisorGradeRoute
  '/supervisor/sessions': typeof SupervisorSessionsRoute
  '/supervisor/student': typeof SupervisorStudentRoute
  '/supervisor/teachers': typeof SupervisorTeachersRoute
  '/supervisor/teachers-hub': typeof SupervisorTeachersHubRoute
  '/supervisor/turbo': typeof SupervisorTurboRoute
  '/teacher/analytics': typeof TeacherAnalyticsRoute
  '/teacher/analyzer': typeof TeacherAnalyzerRoute
  '/teacher/exams': typeof TeacherExamsRoute
  '/teacher/homework': typeof TeacherHomeworkRoute
  '/teacher/log': typeof TeacherLogRoute
  '/teacher/pdf-exams': typeof TeacherPdfExamsRoute
  '/teacher/resources': typeof TeacherResourcesRoute
  '/teacher/schedule': typeof TeacherScheduleRoute
  '/teacher/students': typeof TeacherStudentsRoute
  '/admin/': typeof AdminIndexRoute
  '/parent/': typeof ParentIndexRoute
  '/student/': typeof StudentIndexRoute
  '/supervisor/': typeof SupervisorIndexRoute
  '/teacher/': typeof TeacherIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/parent'
    | '/student'
    | '/supervisor'
    | '/teacher'
    | '/admin/calendar'
    | '/admin/classes'
    | '/admin/content'
    | '/admin/curriculum'
    | '/admin/curriculum-import'
    | '/admin/registration'
    | '/admin/roles'
    | '/admin/schedule'
    | '/admin/system'
    | '/admin/users'
    | '/parent/announcements'
    | '/parent/calendar'
    | '/parent/children'
    | '/parent/companion'
    | '/parent/feedback'
    | '/parent/growth'
    | '/parent/meetings'
    | '/parent/messages'
    | '/parent/reports'
    | '/parent/weekly'
    | '/student/achievements'
    | '/student/analytics'
    | '/student/daily'
    | '/student/exams'
    | '/student/growth'
    | '/student/homework'
    | '/student/lessons'
    | '/student/next-step'
    | '/student/notebook'
    | '/student/planner'
    | '/student/profile'
    | '/student/progress'
    | '/student/resources'
    | '/student/schedule'
    | '/student/tracking'
    | '/student/weekly'
    | '/supervisor/alerts'
    | '/supervisor/analytics'
    | '/supervisor/calendar'
    | '/supervisor/feedback'
    | '/supervisor/followups'
    | '/supervisor/grade'
    | '/supervisor/sessions'
    | '/supervisor/student'
    | '/supervisor/teachers'
    | '/supervisor/teachers-hub'
    | '/supervisor/turbo'
    | '/teacher/analytics'
    | '/teacher/analyzer'
    | '/teacher/exams'
    | '/teacher/homework'
    | '/teacher/log'
    | '/teacher/pdf-exams'
    | '/teacher/resources'
    | '/teacher/schedule'
    | '/teacher/students'
    | '/admin/'
    | '/parent/'
    | '/student/'
    | '/supervisor/'
    | '/teacher/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin/calendar'
    | '/admin/classes'
    | '/admin/content'
    | '/admin/curriculum'
    | '/admin/curriculum-import'
    | '/admin/registration'
    | '/admin/roles'
    | '/admin/schedule'
    | '/admin/system'
    | '/admin/users'
    | '/parent/announcements'
    | '/parent/calendar'
    | '/parent/children'
    | '/parent/companion'
    | '/parent/feedback'
    | '/parent/growth'
    | '/parent/meetings'
    | '/parent/messages'
    | '/parent/reports'
    | '/parent/weekly'
    | '/student/achievements'
    | '/student/analytics'
    | '/student/daily'
    | '/student/exams'
    | '/student/growth'
    | '/student/homework'
    | '/student/lessons'
    | '/student/next-step'
    | '/student/notebook'
    | '/student/planner'
    | '/student/profile'
    | '/student/progress'
    | '/student/resources'
    | '/student/schedule'
    | '/student/tracking'
    | '/student/weekly'
    | '/supervisor/alerts'
    | '/supervisor/analytics'
    | '/supervisor/calendar'
    | '/supervisor/feedback'
    | '/supervisor/followups'
    | '/supervisor/grade'
    | '/supervisor/sessions'
    | '/supervisor/student'
    | '/supervisor/teachers'
    | '/supervisor/teachers-hub'
    | '/supervisor/turbo'
    | '/teacher/analytics'
    | '/teacher/analyzer'
    | '/teacher/exams'
    | '/teacher/homework'
    | '/teacher/log'
    | '/teacher/pdf-exams'
    | '/teacher/resources'
    | '/teacher/schedule'
    | '/teacher/students'
    | '/admin'
    | '/parent'
    | '/student'
    | '/supervisor'
    | '/teacher'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/parent'
    | '/student'
    | '/supervisor'
    | '/teacher'
    | '/admin/calendar'
    | '/admin/classes'
    | '/admin/content'
    | '/admin/curriculum'
    | '/admin/curriculum-import'
    | '/admin/registration'
    | '/admin/roles'
    | '/admin/schedule'
    | '/admin/system'
    | '/admin/users'
    | '/parent/announcements'
    | '/parent/calendar'
    | '/parent/children'
    | '/parent/companion'
    | '/parent/feedback'
    | '/parent/growth'
    | '/parent/meetings'
    | '/parent/messages'
    | '/parent/reports'
    | '/parent/weekly'
    | '/student/achievements'
    | '/student/analytics'
    | '/student/daily'
    | '/student/exams'
    | '/student/growth'
    | '/student/homework'
    | '/student/lessons'
    | '/student/next-step'
    | '/student/notebook'
    | '/student/planner'
    | '/student/profile'
    | '/student/progress'
    | '/student/resources'
    | '/student/schedule'
    | '/student/tracking'
    | '/student/weekly'
    | '/supervisor/alerts'
    | '/supervisor/analytics'
    | '/supervisor/calendar'
    | '/supervisor/feedback'
    | '/supervisor/followups'
    | '/supervisor/grade'
    | '/supervisor/sessions'
    | '/supervisor/student'
    | '/supervisor/teachers'
    | '/supervisor/teachers-hub'
    | '/supervisor/turbo'
    | '/teacher/analytics'
    | '/teacher/analyzer'
    | '/teacher/exams'
    | '/teacher/homework'
    | '/teacher/log'
    | '/teacher/pdf-exams'
    | '/teacher/resources'
    | '/teacher/schedule'
    | '/teacher/students'
    | '/admin/'
    | '/parent/'
    | '/student/'
    | '/supervisor/'
    | '/teacher/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ParentRoute: typeof ParentRouteWithChildren
  StudentRoute: typeof StudentRouteWithChildren
  SupervisorRoute: typeof SupervisorRouteWithChildren
  TeacherRoute: typeof TeacherRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/teacher': {
      id: '/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof TeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/supervisor': {
      id: '/supervisor'
      path: '/supervisor'
      fullPath: '/supervisor'
      preLoaderRoute: typeof SupervisorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/student': {
      id: '/student'
      path: '/student'
      fullPath: '/student'
      preLoaderRoute: typeof StudentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parent': {
      id: '/parent'
      path: '/parent'
      fullPath: '/parent'
      preLoaderRoute: typeof ParentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher/': {
      id: '/teacher/'
      path: '/'
      fullPath: '/teacher/'
      preLoaderRoute: typeof TeacherIndexRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/supervisor/': {
      id: '/supervisor/'
      path: '/'
      fullPath: '/supervisor/'
      preLoaderRoute: typeof SupervisorIndexRouteImport
      parentRoute: typeof SupervisorRoute
    }
    '/student/': {
      id: '/student/'
      path: '/'
      fullPath: '/student/'
      preLoaderRoute: typeof StudentIndexRouteImport
      parentRoute: typeof StudentRoute
    }
    '/parent/': {
      id: '/parent/'
      path: '/'
      fullPath: '/parent/'
      preLoaderRoute: typeof ParentIndexRouteImport
      parentRoute: typeof ParentRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/teacher/students': {
      id: '/teacher/students'
      path: '/students'
      fullPath: '/teacher/students'
      preLoaderRoute: typeof TeacherStudentsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/schedule': {
      id: '/teacher/schedule'
      path: '/schedule'
      fullPath: '/teacher/schedule'
      preLoaderRoute: typeof TeacherScheduleRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/resources': {
      id: '/teacher/resources'
      path: '/resources'
      fullPath: '/teacher/resources'
      preLoaderRoute: typeof TeacherResourcesRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/pdf-exams': {
      id: '/teacher/pdf-exams'
      path: '/pdf-exams'
      fullPath: '/teacher/pdf-exams'
      preLoaderRoute: typeof TeacherPdfExamsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/log': {
      id: '/teacher/log'
      path: '/log'
      fullPath: '/teacher/log'
      preLoaderRoute: typeof TeacherLogRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/homework': {
      id: '/teacher/homework'
      path: '/homework'
      fullPath: '/teacher/homework'
      preLoaderRoute: typeof TeacherHomeworkRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/exams': {
      id: '/teacher/exams'
      path: '/exams'
      fullPath: '/teacher/exams'
      preLoaderRoute: typeof TeacherExamsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/analyzer': {
      id: '/teacher/analyzer'
      path: '/analyzer'
      fullPath: '/teacher/analyzer'
      preLoaderRoute: typeof TeacherAnalyzerRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/teacher/analytics': {
      id: '/teacher/analytics'
      path: '/analytics'
      fullPath: '/teacher/analytics'
      preLoaderRoute: typeof TeacherAnalyticsRouteImport
      parentRoute: typeof TeacherRoute
    }
    '/supervisor/turbo': {
      id: '/supervisor/turbo'
      path: '/turbo'
      fullPath: '/supervisor/turbo'
      preLoaderRoute: typeof SupervisorTurboRouteImport
      parentRoute: typeof SupervisorRoute
    }
    '/supervisor/teachers-hub': {
      id: '/supervisor/teachers-hub'
      path: '/teachers-hub'
      fullPath: '/supervisor/teachers-hub'
      preLoaderRoute: typeof SupervisorTeachersHubRouteImport
      parentRoute: typeof SupervisorRoute
    }
    '/supervisor/teachers': {
      id: '/supervisor/teachers'
      path: '/teachers'
      fullPath: '/supervisor/teachers'
      preLoaderRoute: typeof SupervisorTeachersRouteImport
      parentRoute: typeof SupervisorRoute
    }
    '/supervisor/student': {
      id: '/supervisor/student'
      path: '/student'
      fullPath: '/supervisor/student'
      preLoaderRoute: typeof SupervisorStudentRouteImport
      parentRoute: typeof SupervisorRoute
    }
    '/supervisor/sessions': {
      id: '/supervisor/sessions'
      path: '/sessions'
      fullPath: '/supervisor/sessions'
      preLoaderRoute: typeof SupervisorSessionsRouteImport
      parentRoute: typeof SupervisorRoute
    }
    '/supervisor/grade': {
      id: '/supervisor/grade'
      path: '/grade'
      fullPath: '/supervisor/grade'
      preLoaderRoute: typeof SupervisorGradeRouteImport
      parentRoute: typeof SupervisorRoute
    }
    '/supervisor/followups': {
      id: '/supervisor/followups'
      path: '/followups'
      fullPath: '/supervisor/followups'
      preLoaderRoute: typeof SupervisorFollowupsRouteImport
      parentRoute: typeof SupervisorRoute
    }
    '/supervisor/feedback': {
      id: '/supervisor/feedback'
      path: '/feedback'
      fullPath: '/supervisor/feedback'
      preLoaderRoute: typeof SupervisorFeedbackRouteImport
      parentRoute: typeof SupervisorRoute
    }
    '/supervisor/calendar': {
      id: '/supervisor/calendar'
      path: '/calendar'
      fullPath: '/supervisor/calendar'
      preLoaderRoute: typeof SupervisorCalendarRouteImport
      parentRoute: typeof SupervisorRoute
    }
    '/supervisor/analytics': {
      id: '/supervisor/analytics'
      path: '/analytics'
      fullPath: '/supervisor/analytics'
      preLoaderRoute: typeof SupervisorAnalyticsRouteImport
      parentRoute: typeof SupervisorRoute
    }
    '/supervisor/alerts': {
      id: '/supervisor/alerts'
      path: '/alerts'
      fullPath: '/supervisor/alerts'
      preLoaderRoute: typeof SupervisorAlertsRouteImport
      parentRoute: typeof SupervisorRoute
    }
    '/student/weekly': {
      id: '/student/weekly'
      path: '/weekly'
      fullPath: '/student/weekly'
      preLoaderRoute: typeof StudentWeeklyRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/tracking': {
      id: '/student/tracking'
      path: '/tracking'
      fullPath: '/student/tracking'
      preLoaderRoute: typeof StudentTrackingRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/schedule': {
      id: '/student/schedule'
      path: '/schedule'
      fullPath: '/student/schedule'
      preLoaderRoute: typeof StudentScheduleRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/resources': {
      id: '/student/resources'
      path: '/resources'
      fullPath: '/student/resources'
      preLoaderRoute: typeof StudentResourcesRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/progress': {
      id: '/student/progress'
      path: '/progress'
      fullPath: '/student/progress'
      preLoaderRoute: typeof StudentProgressRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/profile': {
      id: '/student/profile'
      path: '/profile'
      fullPath: '/student/profile'
      preLoaderRoute: typeof StudentProfileRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/planner': {
      id: '/student/planner'
      path: '/planner'
      fullPath: '/student/planner'
      preLoaderRoute: typeof StudentPlannerRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/notebook': {
      id: '/student/notebook'
      path: '/notebook'
      fullPath: '/student/notebook'
      preLoaderRoute: typeof StudentNotebookRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/next-step': {
      id: '/student/next-step'
      path: '/next-step'
      fullPath: '/student/next-step'
      preLoaderRoute: typeof StudentNextStepRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/lessons': {
      id: '/student/lessons'
      path: '/lessons'
      fullPath: '/student/lessons'
      preLoaderRoute: typeof StudentLessonsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/homework': {
      id: '/student/homework'
      path: '/homework'
      fullPath: '/student/homework'
      preLoaderRoute: typeof StudentHomeworkRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/growth': {
      id: '/student/growth'
      path: '/growth'
      fullPath: '/student/growth'
      preLoaderRoute: typeof StudentGrowthRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/exams': {
      id: '/student/exams'
      path: '/exams'
      fullPath: '/student/exams'
      preLoaderRoute: typeof StudentExamsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/daily': {
      id: '/student/daily'
      path: '/daily'
      fullPath: '/student/daily'
      preLoaderRoute: typeof StudentDailyRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/analytics': {
      id: '/student/analytics'
      path: '/analytics'
      fullPath: '/student/analytics'
      preLoaderRoute: typeof StudentAnalyticsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/student/achievements': {
      id: '/student/achievements'
      path: '/achievements'
      fullPath: '/student/achievements'
      preLoaderRoute: typeof StudentAchievementsRouteImport
      parentRoute: typeof StudentRoute
    }
    '/parent/weekly': {
      id: '/parent/weekly'
      path: '/weekly'
      fullPath: '/parent/weekly'
      preLoaderRoute: typeof ParentWeeklyRouteImport
      parentRoute: typeof ParentRoute
    }
    '/parent/reports': {
      id: '/parent/reports'
      path: '/reports'
      fullPath: '/parent/reports'
      preLoaderRoute: typeof ParentReportsRouteImport
      parentRoute: typeof ParentRoute
    }
    '/parent/messages': {
      id: '/parent/messages'
      path: '/messages'
      fullPath: '/parent/messages'
      preLoaderRoute: typeof ParentMessagesRouteImport
      parentRoute: typeof ParentRoute
    }
    '/parent/meetings': {
      id: '/parent/meetings'
      path: '/meetings'
      fullPath: '/parent/meetings'
      preLoaderRoute: typeof ParentMeetingsRouteImport
      parentRoute: typeof ParentRoute
    }
    '/parent/growth': {
      id: '/parent/growth'
      path: '/growth'
      fullPath: '/parent/growth'
      preLoaderRoute: typeof ParentGrowthRouteImport
      parentRoute: typeof ParentRoute
    }
    '/parent/feedback': {
      id: '/parent/feedback'
      path: '/feedback'
      fullPath: '/parent/feedback'
      preLoaderRoute: typeof ParentFeedbackRouteImport
      parentRoute: typeof ParentRoute
    }
    '/parent/companion': {
      id: '/parent/companion'
      path: '/companion'
      fullPath: '/parent/companion'
      preLoaderRoute: typeof ParentCompanionRouteImport
      parentRoute: typeof ParentRoute
    }
    '/parent/children': {
      id: '/parent/children'
      path: '/children'
      fullPath: '/parent/children'
      preLoaderRoute: typeof ParentChildrenRouteImport
      parentRoute: typeof ParentRoute
    }
    '/parent/calendar': {
      id: '/parent/calendar'
      path: '/calendar'
      fullPath: '/parent/calendar'
      preLoaderRoute: typeof ParentCalendarRouteImport
      parentRoute: typeof ParentRoute
    }
    '/parent/announcements': {
      id: '/parent/announcements'
      path: '/announcements'
      fullPath: '/parent/announcements'
      preLoaderRoute: typeof ParentAnnouncementsRouteImport
      parentRoute: typeof ParentRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/system': {
      id: '/admin/system'
      path: '/system'
      fullPath: '/admin/system'
      preLoaderRoute: typeof AdminSystemRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/schedule': {
      id: '/admin/schedule'
      path: '/schedule'
      fullPath: '/admin/schedule'
      preLoaderRoute: typeof AdminScheduleRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/registration': {
      id: '/admin/registration'
      path: '/registration'
      fullPath: '/admin/registration'
      preLoaderRoute: typeof AdminRegistrationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/curriculum-import': {
      id: '/admin/curriculum-import'
      path: '/curriculum-import'
      fullPath: '/admin/curriculum-import'
      preLoaderRoute: typeof AdminCurriculumImportRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/curriculum': {
      id: '/admin/curriculum'
      path: '/curriculum'
      fullPath: '/admin/curriculum'
      preLoaderRoute: typeof AdminCurriculumRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/content': {
      id: '/admin/content'
      path: '/content'
      fullPath: '/admin/content'
      preLoaderRoute: typeof AdminContentRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/classes': {
      id: '/admin/classes'
      path: '/classes'
      fullPath: '/admin/classes'
      preLoaderRoute: typeof AdminClassesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/calendar': {
      id: '/admin/calendar'
      path: '/calendar'
      fullPath: '/admin/calendar'
      preLoaderRoute: typeof AdminCalendarRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminCalendarRoute: typeof AdminCalendarRoute
  AdminClassesRoute: typeof AdminClassesRoute
  AdminContentRoute: typeof AdminContentRoute
  AdminCurriculumRoute: typeof AdminCurriculumRoute
  AdminCurriculumImportRoute: typeof AdminCurriculumImportRoute
  AdminRegistrationRoute: typeof AdminRegistrationRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AdminScheduleRoute: typeof AdminScheduleRoute
  AdminSystemRoute: typeof AdminSystemRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminCalendarRoute: AdminCalendarRoute,
  AdminClassesRoute: AdminClassesRoute,
  AdminContentRoute: AdminContentRoute,
  AdminCurriculumRoute: AdminCurriculumRoute,
  AdminCurriculumImportRoute: AdminCurriculumImportRoute,
  AdminRegistrationRoute: AdminRegistrationRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminScheduleRoute: AdminScheduleRoute,
  AdminSystemRoute: AdminSystemRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ParentRouteChildren {
  ParentAnnouncementsRoute: typeof ParentAnnouncementsRoute
  ParentCalendarRoute: typeof ParentCalendarRoute
  ParentChildrenRoute: typeof ParentChildrenRoute
  ParentCompanionRoute: typeof ParentCompanionRoute
  ParentFeedbackRoute: typeof ParentFeedbackRoute
  ParentGrowthRoute: typeof ParentGrowthRoute
  ParentMeetingsRoute: typeof ParentMeetingsRoute
  ParentMessagesRoute: typeof ParentMessagesRoute
  ParentReportsRoute: typeof ParentReportsRoute
  ParentWeeklyRoute: typeof ParentWeeklyRoute
  ParentIndexRoute: typeof ParentIndexRoute
}

const ParentRouteChildren: ParentRouteChildren = {
  ParentAnnouncementsRoute: ParentAnnouncementsRoute,
  ParentCalendarRoute: ParentCalendarRoute,
  ParentChildrenRoute: ParentChildrenRoute,
  ParentCompanionRoute: ParentCompanionRoute,
  ParentFeedbackRoute: ParentFeedbackRoute,
  ParentGrowthRoute: ParentGrowthRoute,
  ParentMeetingsRoute: ParentMeetingsRoute,
  ParentMessagesRoute: ParentMessagesRoute,
  ParentReportsRoute: ParentReportsRoute,
  ParentWeeklyRoute: ParentWeeklyRoute,
  ParentIndexRoute: ParentIndexRoute,
}

const ParentRouteWithChildren =
  ParentRoute._addFileChildren(ParentRouteChildren)

interface StudentRouteChildren {
  StudentAchievementsRoute: typeof StudentAchievementsRoute
  StudentAnalyticsRoute: typeof StudentAnalyticsRoute
  StudentDailyRoute: typeof StudentDailyRoute
  StudentExamsRoute: typeof StudentExamsRoute
  StudentGrowthRoute: typeof StudentGrowthRoute
  StudentHomeworkRoute: typeof StudentHomeworkRoute
  StudentLessonsRoute: typeof StudentLessonsRoute
  StudentNextStepRoute: typeof StudentNextStepRoute
  StudentNotebookRoute: typeof StudentNotebookRoute
  StudentPlannerRoute: typeof StudentPlannerRoute
  StudentProfileRoute: typeof StudentProfileRoute
  StudentProgressRoute: typeof StudentProgressRoute
  StudentResourcesRoute: typeof StudentResourcesRoute
  StudentScheduleRoute: typeof StudentScheduleRoute
  StudentTrackingRoute: typeof StudentTrackingRoute
  StudentWeeklyRoute: typeof StudentWeeklyRoute
  StudentIndexRoute: typeof StudentIndexRoute
}

const StudentRouteChildren: StudentRouteChildren = {
  StudentAchievementsRoute: StudentAchievementsRoute,
  StudentAnalyticsRoute: StudentAnalyticsRoute,
  StudentDailyRoute: StudentDailyRoute,
  StudentExamsRoute: StudentExamsRoute,
  StudentGrowthRoute: StudentGrowthRoute,
  StudentHomeworkRoute: StudentHomeworkRoute,
  StudentLessonsRoute: StudentLessonsRoute,
  StudentNextStepRoute: StudentNextStepRoute,
  StudentNotebookRoute: StudentNotebookRoute,
  StudentPlannerRoute: StudentPlannerRoute,
  StudentProfileRoute: StudentProfileRoute,
  StudentProgressRoute: StudentProgressRoute,
  StudentResourcesRoute: StudentResourcesRoute,
  StudentScheduleRoute: StudentScheduleRoute,
  StudentTrackingRoute: StudentTrackingRoute,
  StudentWeeklyRoute: StudentWeeklyRoute,
  StudentIndexRoute: StudentIndexRoute,
}

const StudentRouteWithChildren =
  StudentRoute._addFileChildren(StudentRouteChildren)

interface SupervisorRouteChildren {
  SupervisorAlertsRoute: typeof SupervisorAlertsRoute
  SupervisorAnalyticsRoute: typeof SupervisorAnalyticsRoute
  SupervisorCalendarRoute: typeof SupervisorCalendarRoute
  SupervisorFeedbackRoute: typeof SupervisorFeedbackRoute
  SupervisorFollowupsRoute: typeof SupervisorFollowupsRoute
  SupervisorGradeRoute: typeof SupervisorGradeRoute
  SupervisorSessionsRoute: typeof SupervisorSessionsRoute
  SupervisorStudentRoute: typeof SupervisorStudentRoute
  SupervisorTeachersRoute: typeof SupervisorTeachersRoute
  SupervisorTeachersHubRoute: typeof SupervisorTeachersHubRoute
  SupervisorTurboRoute: typeof SupervisorTurboRoute
  SupervisorIndexRoute: typeof SupervisorIndexRoute
}

const SupervisorRouteChildren: SupervisorRouteChildren = {
  SupervisorAlertsRoute: SupervisorAlertsRoute,
  SupervisorAnalyticsRoute: SupervisorAnalyticsRoute,
  SupervisorCalendarRoute: SupervisorCalendarRoute,
  SupervisorFeedbackRoute: SupervisorFeedbackRoute,
  SupervisorFollowupsRoute: SupervisorFollowupsRoute,
  SupervisorGradeRoute: SupervisorGradeRoute,
  SupervisorSessionsRoute: SupervisorSessionsRoute,
  SupervisorStudentRoute: SupervisorStudentRoute,
  SupervisorTeachersRoute: SupervisorTeachersRoute,
  SupervisorTeachersHubRoute: SupervisorTeachersHubRoute,
  SupervisorTurboRoute: SupervisorTurboRoute,
  SupervisorIndexRoute: SupervisorIndexRoute,
}

const SupervisorRouteWithChildren = SupervisorRoute._addFileChildren(
  SupervisorRouteChildren,
)

interface TeacherRouteChildren {
  TeacherAnalyticsRoute: typeof TeacherAnalyticsRoute
  TeacherAnalyzerRoute: typeof TeacherAnalyzerRoute
  TeacherExamsRoute: typeof TeacherExamsRoute
  TeacherHomeworkRoute: typeof TeacherHomeworkRoute
  TeacherLogRoute: typeof TeacherLogRoute
  TeacherPdfExamsRoute: typeof TeacherPdfExamsRoute
  TeacherResourcesRoute: typeof TeacherResourcesRoute
  TeacherScheduleRoute: typeof TeacherScheduleRoute
  TeacherStudentsRoute: typeof TeacherStudentsRoute
  TeacherIndexRoute: typeof TeacherIndexRoute
}

const TeacherRouteChildren: TeacherRouteChildren = {
  TeacherAnalyticsRoute: TeacherAnalyticsRoute,
  TeacherAnalyzerRoute: TeacherAnalyzerRoute,
  TeacherExamsRoute: TeacherExamsRoute,
  TeacherHomeworkRoute: TeacherHomeworkRoute,
  TeacherLogRoute: TeacherLogRoute,
  TeacherPdfExamsRoute: TeacherPdfExamsRoute,
  TeacherResourcesRoute: TeacherResourcesRoute,
  TeacherScheduleRoute: TeacherScheduleRoute,
  TeacherStudentsRoute: TeacherStudentsRoute,
  TeacherIndexRoute: TeacherIndexRoute,
}

const TeacherRouteWithChildren =
  TeacherRoute._addFileChildren(TeacherRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ParentRoute: ParentRouteWithChildren,
  StudentRoute: StudentRouteWithChildren,
  SupervisorRoute: SupervisorRouteWithChildren,
  TeacherRoute: TeacherRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
