import { createStart, createMiddleware } from "@tanstack/react-start";

import { renderErrorPage } from "./lib/error-page";

// ─────────────────────────────────────────────────────────────────────────────
// IMPORTANT — DO NOT re-add `attachSupabaseAuth` here.
//
// Atomia authenticates via Xano, not Supabase. The `src/integrations/supabase/`
// directory is auto-regenerated by the Lovable Cloud platform (the toggle lives
// in the Lovable dashboard, not in this repo) and cannot be permanently deleted
// from code. That is fine: nothing in `src/` (outside that directory itself)
// imports from it — grep confirms zero references — so those files are inert
// dead code and safe to ignore.
//
// However, the platform also re-adds `attachSupabaseAuth` to this middleware
// array when it regenerates. If you see it come back, REMOVE IT. Registering
// it triggers `supabase.auth.getSession()` on every server-fn call, which is
// wasted work (and misleading) for a Xano-authed app.
// ─────────────────────────────────────────────────────────────────────────────

const errorMiddleware = createMiddleware().server(async ({ next }) => {
  try {
    return await next();
  } catch (error) {
    if (error != null && typeof error === "object" && "statusCode" in error) {
      throw error;
    }
    console.error(error);
    return new Response(renderErrorPage(), {
      status: 500,
      headers: { "content-type": "text/html; charset=utf-8" },
    });
  }
});

export const startInstance = createStart(() => ({
  functionMiddleware: [],
  requestMiddleware: [errorMiddleware],
}));
